[[redirects]]
  from = "/api/*"
  to = "http://Confide-env-1.eba-geg4zhf4.ap-northeast-2.elasticbeanstalk.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200